import { RightGroupPage } from './RightGroupPage';

export const RIGHTGROUPPAGE: RightGroupPage[] = [
    { 
        id: 1, 
        name: "default",
        access_Main: true, 
        access_Accueil: true, 
        access_Login: true, 
        access_MonCompte: false, 
        access_Main_EditBar: false, 
        SelectedUserManagement_Access: false, 
        SelectedUserManagement_ViewPassword: false,
        SelectedUserManagement_ShowPasswordButton: false,
        SelectedUserManagement_EditRightGroupPageUser: false,
        SelectedUserManagement_DeleteUser: false,
        SelectedUserManagement_EditUser: false,
        UserManagement_Access: false, 
        UserManagement_AddUser: false,
        UserManagement_EditDefaultUser: false,
        GroupManagement_Access: false,
        GroupManagement_AddGroup: false,
        GroupManagement_EditDefaultGroup: false,
        access_Main_EditBar_Dev: false, 
        access_Main_EditBar_Edit: false
    },
    { 
        id: 2, 
        name : "Développement",
        access_Main: true, 
        access_Accueil: true, 
        access_Login: true, 
        access_MonCompte: true, 
        access_Main_EditBar: true, 
        SelectedUserManagement_Access: true, 
        SelectedUserManagement_ViewPassword: true,
        SelectedUserManagement_ShowPasswordButton: true,
        SelectedUserManagement_EditRightGroupPageUser: true,
        SelectedUserManagement_DeleteUser: true,
        SelectedUserManagement_EditUser: true,
        UserManagement_Access: true, 
        UserManagement_AddUser: true,
        UserManagement_EditDefaultUser: true,
        GroupManagement_Access: true,
        GroupManagement_AddGroup: true,
        GroupManagement_EditDefaultGroup: true,
        access_Main_EditBar_Dev: true, 
        access_Main_EditBar_Edit: true
    }
];